# Generated by Django 4.2 on 2024-10-27 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Vidyarthi',
        ),
    ]
